### ISSUE TITLE
Server Crash with Extra Utilities

### ISSUE THREAD

**Issue by CamouFlugeL** [KAMKEEL/Plugin-Mod#1]
Hello. I started the server with Extra Utilities and Plugin Mod. As a result , it crashed:
[crash-2022-04-26_22.32.55-server.txt](https://github.com/KAMKEEL/Plugin-Mod/files/8566421/crash-2022-04-26_22.32.55-server.txt)

**Comment by KAMKEEL** [comment]
Are you using the latest version of Extra Utils?

**Comment by KAMKEEL** [comment]
No Response
